"""add_surah_name_to_hafalan_table

Revision ID: 9be68f162d9f
Revises: 64e15c898f87
Create Date: 2025-05-29 16:49:45.541168

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9be68f162d9f'
down_revision = '64e15c898f87'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ayahs', sa.Column('ayah_number_in_surah', sa.Integer(), nullable=False))
    op.add_column('ayahs', sa.Column('text_uthmani', sa.Text(), nullable=False))
    op.add_column('ayahs', sa.Column('translation_id', sa.Text(), nullable=True))
    op.add_column('ayahs', sa.Column('translation_en', sa.Text(), nullable=True))
    op.create_index(op.f('ix_ayahs_id'), 'ayahs', ['id'], unique=False)
    op.create_index(op.f('ix_ayahs_surah_id'), 'ayahs', ['surah_id'], unique=False)
    op.drop_constraint('fk_ayahs_surah_id_surahs', 'ayahs', type_='foreignkey')
    op.create_foreign_key(op.f('fk_ayahs_surah_id_surahs'), 'ayahs', 'surahs', ['surah_id'], ['id'], ondelete='CASCADE')
    op.drop_column('ayahs', 'text')
    op.drop_column('ayahs', 'number_in_surah')
    op.add_column('hafalan', sa.Column('surah_name', sa.String(length=100), nullable=True))
    op.add_column('hafalan', sa.Column('ayah_range', sa.String(length=50), nullable=True))
    op.add_column('hafalan', sa.Column('catatan', sa.Text(), nullable=True))
    op.add_column('hafalan', sa.Column('last_reviewed_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.alter_column('hafalan', 'ayah_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_hafalan_id'), 'hafalan', ['id'], unique=False)
    op.create_index(op.f('ix_hafalan_user_id'), 'hafalan', ['user_id'], unique=False)
    op.drop_constraint('fk_hafalan_ayah_id_ayahs', 'hafalan', type_='foreignkey')
    op.drop_constraint('fk_hafalan_user_id_users', 'hafalan', type_='foreignkey')
    op.create_foreign_key(op.f('fk_hafalan_user_id_users'), 'hafalan', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_hafalan_ayah_id_ayahs'), 'hafalan', 'ayahs', ['ayah_id'], ['id'], ondelete='SET NULL')
    op.alter_column('reminders', 'is_completed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('reminders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_reminders_due_date'), 'reminders', ['due_date'], unique=False)
    op.create_index(op.f('ix_reminders_id'), 'reminders', ['id'], unique=False)
    op.create_index(op.f('ix_reminders_user_id'), 'reminders', ['user_id'], unique=False)
    op.drop_column('reminders', 'updated_at')
    op.drop_column('reminders', 'catatan')
    op.drop_column('reminders', 'juz')
    op.drop_column('reminders', 'halaman')
    op.add_column('surahs', sa.Column('surah_number', sa.Integer(), nullable=False))
    op.add_column('surahs', sa.Column('name_arabic', sa.String(length=100), nullable=False))
    op.add_column('surahs', sa.Column('name_english', sa.String(length=100), nullable=False))
    op.add_column('surahs', sa.Column('english_translation', sa.String(length=100), nullable=True))
    op.add_column('surahs', sa.Column('revelation_type', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_surahs_id'), 'surahs', ['id'], unique=False)
    op.create_index(op.f('ix_surahs_surah_number'), 'surahs', ['surah_number'], unique=True)
    op.drop_column('surahs', 'name')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('uq_users_email', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('uq_users_email', 'users', ['email'])
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.add_column('surahs', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_surahs_surah_number'), table_name='surahs')
    op.drop_index(op.f('ix_surahs_id'), table_name='surahs')
    op.drop_column('surahs', 'revelation_type')
    op.drop_column('surahs', 'english_translation')
    op.drop_column('surahs', 'name_english')
    op.drop_column('surahs', 'name_arabic')
    op.drop_column('surahs', 'surah_number')
    op.add_column('reminders', sa.Column('halaman', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('reminders', sa.Column('juz', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('reminders', sa.Column('catatan', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('reminders', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_reminders_user_id'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_id'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_due_date'), table_name='reminders')
    op.alter_column('reminders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('reminders', 'is_completed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_constraint(op.f('fk_hafalan_ayah_id_ayahs'), 'hafalan', type_='foreignkey')
    op.drop_constraint(op.f('fk_hafalan_user_id_users'), 'hafalan', type_='foreignkey')
    op.create_foreign_key('fk_hafalan_user_id_users', 'hafalan', 'users', ['user_id'], ['id'])
    op.create_foreign_key('fk_hafalan_ayah_id_ayahs', 'hafalan', 'ayahs', ['ayah_id'], ['id'])
    op.drop_index(op.f('ix_hafalan_user_id'), table_name='hafalan')
    op.drop_index(op.f('ix_hafalan_id'), table_name='hafalan')
    op.alter_column('hafalan', 'ayah_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('hafalan', 'last_reviewed_at')
    op.drop_column('hafalan', 'catatan')
    op.drop_column('hafalan', 'ayah_range')
    op.drop_column('hafalan', 'surah_name')
    op.add_column('ayahs', sa.Column('number_in_surah', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('ayahs', sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_ayahs_surah_id_surahs'), 'ayahs', type_='foreignkey')
    op.create_foreign_key('fk_ayahs_surah_id_surahs', 'ayahs', 'surahs', ['surah_id'], ['id'])
    op.drop_index(op.f('ix_ayahs_surah_id'), table_name='ayahs')
    op.drop_index(op.f('ix_ayahs_id'), table_name='ayahs')
    op.drop_column('ayahs', 'translation_en')
    op.drop_column('ayahs', 'translation_id')
    op.drop_column('ayahs', 'text_uthmani')
    op.drop_column('ayahs', 'ayah_number_in_surah')
    # ### end Alembic commands ###
